# Generated by Django 5.2.7 on 2025-11-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('romance', 'Romance'), ('adventure', 'Adventure'), ('history', 'History'), ('horror', 'Horror'), ('folklore', 'Folklore'), ('motivational', 'Motivational')], max_length=100)),
            ],
        ),
    ]
